[package]
name = "server-tools"
version = "0.1.0"
authors = ["Thibault “Adædra” Hamel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
log = "0.4"
flexi_logger = "0.15"
zfs = { path = "../zfs" }
